spring:
#  use "jdbc:h2:tcp://localhost/mem:public” for external connections
  datasource:
    url: jdbc:h2:mem:public;
    username: sa
    password: sa
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate:
              trace